language: generic


matrix:
  include:
    - os: osx
      osx_image: xcode12

    - os: osx
      osx_image: xcode11.3

    - os: osx
      osx_image: xcode10.1


install:
  - brew install --build-from-source Formula/sshpass.rb
  - brew install --build-from-source Formula/steghide.rb

script:
  - sshpass --version
  - steghide --version
