name: pkg-test


on:
  push:
    tags: ['v*']
    paths: ['Formula/**']


jobs:
  pkg-test:
    runs-on: macos-latest

    steps:
      - name: Tap repository
        run: brew tap caian-org/formulas

      - name: Install programs
        run: |
          brew install sshpass
          brew install steghide
          brew install tmux31c

      - name: Run programs
        run: |
          sshpass
          steghide
          tmux -V
