name: run-test

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - "*"
    tags:
      - "*"
    paths-ignore:
      - "**.md"

jobs:
  run-test:
    runs-on: macos-latest

    steps:
      - name: Checkout to vrelease-formula
        uses: actions/checkout@v2

      - name: Install formulas from source
        run: |
          brew install --formula ./Formula/sshpass.rb
          brew install --formula ./Formula/steghide.rb
          brew install --formula ./Formula/tmux31c.rb

      - name: Run programs
        run: |
          sshpass
          steghide
